name: Deployment

on:
  push:
    branches:
      - production

jobs:
  prod-check:
      if: ${{ github.ref_name == 'production' }}
      runs-on: ubuntu-latest
      environment: production
      concurrency: production
      steps:
        - name: deploy
          run: echo "Midterm1"
        
    
